//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPEXAMEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_jugadores
    {
        public int idjugador { get; set; }
        public int numero { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public string nacionalidad { get; set; }
        public string pie { get; set; }
        public string puesto { get; set; }
        public string altura { get; set; }
        public string valor { get; set; }
        public int goles { get; set; }
        public int tarjetas { get; set; }
    }
}
